version: "3"
services:
  web:
    image: s140035/cloudsysteenpart2:latest
    command: php -S 0.0.0.0:5000 -t /app
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=""
      - MYSQL_DATABASE=rolodex
      - MYSQL_USER=DennisM
      - MYSQL_PASSWORD=Eternatus!
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
